server:
  port: 7000
  servlet:
    context-path: /core
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
aws:
  iam:
    user:
      accessKey: 
      secretKey: 
  sqs:
    queueUrl: 
    delayInSeconds: 5
  region: eu-west-1       

