server:
  port: 7000
  servlet:
    context-path: /core
spring:
  datasource:
    url: jdbc:mysql://34.241.157.142:3306/moidb
    username: moiadmin
    password: Admin@1234
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
     # ddl-auto: create  
aws:
  iam:
    user:
      accessKey: 
      secretKey: 
  sqs:
    queueUrl: 
    delayInSeconds: 5
  region: eu-west-1 