server:
  port: 9000
  servlet:
    context-path: /core
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB}
    username: ${DB_USER}
    password: ${PASSWORD}
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
logging:
   file: ../Logs/${spring.application.name}.log         
aws:
  iam:
    user:
      accessKey: 
      secretKey: 
  sqs:
    queueUrl: 
    delayInSeconds: 5
  region: eu-west-1 